//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API.DemandSubAccount {

    /**
    Get demand sub-accounts

    Get a list of demand sub-accounts filtered by relevant query parameters
    */
    public enum GetDemandSubAccounts {

        public static let service = APIService<Response>(id: "getDemandSubAccounts", tag: "Demand Sub-Account", method: "GET", path: "/demandSubAccounts", hasBody: false, securityRequirements: [SecurityRequirement(type: "oauth", scopes: ["finance:read"])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** A comma separated list of ids */
                public var id: [Int]?

                /** A comma separated list of uuids */
                public var uuid: [ID]?

                /** A comma separated list of account ids */
                public var accountId: [Int]?

                /** A comma separated list of names */
                public var name: [String]?

                /** A comma separated list of company uuids */
                public var companyUuid: [ID]?

                /** A comma separated list of sub account display names */
                public var displayName: [String]?

                public var productType: [EvenProductType]?

                /** comma separated list of uuids */
                public var createdBy: [ID]?

                /** creation date of object */
                public var createdAt: DateTime?

                /** ignored deleted items, default true */
                public var excludeDeleted: Bool?

                /** include deactivated items, default false */
                public var includeDeactivated: Bool?

                /** limit results */
                public var limit: Int

                /** at what offset do you want to start looking at, default 0 */
                public var offset: Int?

                /** how do you want to sort, default created_at */
                public var sortBy: String?

                public var order: EvenOrder?

                public init(id: [Int]? = nil, uuid: [ID]? = nil, accountId: [Int]? = nil, name: [String]? = nil, companyUuid: [ID]? = nil, displayName: [String]? = nil, productType: [EvenProductType]? = nil, createdBy: [ID]? = nil, createdAt: DateTime? = nil, excludeDeleted: Bool? = nil, includeDeactivated: Bool? = nil, limit: Int, offset: Int? = nil, sortBy: String? = nil, order: EvenOrder? = nil) {
                    self.id = id
                    self.uuid = uuid
                    self.accountId = accountId
                    self.name = name
                    self.companyUuid = companyUuid
                    self.displayName = displayName
                    self.productType = productType
                    self.createdBy = createdBy
                    self.createdAt = createdAt
                    self.excludeDeleted = excludeDeleted
                    self.includeDeactivated = includeDeactivated
                    self.limit = limit
                    self.offset = offset
                    self.sortBy = sortBy
                    self.order = order
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetDemandSubAccounts.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(id: [Int]? = nil, uuid: [ID]? = nil, accountId: [Int]? = nil, name: [String]? = nil, companyUuid: [ID]? = nil, displayName: [String]? = nil, productType: [EvenProductType]? = nil, createdBy: [ID]? = nil, createdAt: DateTime? = nil, excludeDeleted: Bool? = nil, includeDeactivated: Bool? = nil, limit: Int, offset: Int? = nil, sortBy: String? = nil, order: EvenOrder? = nil) {
                let options = Options(id: id, uuid: uuid, accountId: accountId, name: name, companyUuid: companyUuid, displayName: displayName, productType: productType, createdBy: createdBy, createdAt: createdAt, excludeDeleted: excludeDeleted, includeDeactivated: includeDeactivated, limit: limit, offset: offset, sortBy: sortBy, order: order)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let id = options.id?.map({ String(describing: $0) }).joined(separator: ",") {
                  params["id"] = id
                }
                if let uuid = options.uuid?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["uuid"] = uuid
                }
                if let accountId = options.accountId?.map({ String(describing: $0) }).joined(separator: ",") {
                  params["accountId"] = accountId
                }
                if let name = options.name?.joined(separator: ",") {
                  params["name"] = name
                }
                if let companyUuid = options.companyUuid?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["companyUuid"] = companyUuid
                }
                if let displayName = options.displayName?.joined(separator: ",") {
                  params["displayName"] = displayName
                }
                if let productType = options.productType?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["productType"] = productType
                }
                if let createdBy = options.createdBy?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["createdBy"] = createdBy
                }
                if let createdAt = options.createdAt?.encode() {
                  params["createdAt"] = createdAt
                }
                if let excludeDeleted = options.excludeDeleted {
                  params["excludeDeleted"] = excludeDeleted
                }
                if let includeDeactivated = options.includeDeactivated {
                  params["includeDeactivated"] = includeDeactivated
                }
                params["limit"] = options.limit
                if let offset = options.offset {
                  params["offset"] = offset
                }
                if let sortBy = options.sortBy {
                  params["sortBy"] = sortBy
                }
                if let order = options.order?.encode() {
                  params["order"] = order
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = [EvenDemandSubAccount]

            /** Success */
            case status200([EvenDemandSubAccount])

            /** Invalid request */
            case status400([EvenApiError])

            public var success: [EvenDemandSubAccount]? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var failure: [EvenApiError]? {
                switch self {
                case .status400(let response): return response
                default: return nil
                }
            }

            /// either success or failure value. Success is anything in the 200..<300 status code range
            public var responseResult: APIResponseResult<[EvenDemandSubAccount], [EvenApiError]> {
                if let successValue = success {
                    return .success(successValue)
                } else if let failureValue = failure {
                    return .failure(failureValue)
                } else {
                    fatalError("Response does not have success or failure response")
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .status400(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode([EvenDemandSubAccount].self, from: data))
                case 400: self = try .status400(decoder.decode([EvenApiError].self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
