openapi: 3.0.3
info:
  title: finance
  description: Home to various finance-related functions
  version: 1.10.0
  contact:
    name: Finance Team
    url: >-
      https://evenfinancial.atlassian.net/wiki/spaces/ENG/pages/36044820/Finance+Team
servers:
  - url: 'https://api.evenfinancial.com/finance'
    description: Prod
  - url: 'https://dev-api.evenfinancial.com/finance'
    description: Dev
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /auth/accessTokens
          scopes:
            'finance:read': Allows read access to svc-finance resources
            'finance:write': Allows write access to svc-finance resources
tags:
  - name: Account
    description: >-
      Accounts are representations of our supply and demand partners. Each
      account contains identifying information about the partner including
      billing related requirements.
  - name: Account Adjustment
    description: >-
      Adjustments are applied to a payable or receivable to reconcile any
      monetary differences not captured in our system.
  - name: Account Deactivation
  - name: Billing Cycle
    description: >-
      Billing cycles are a schedyle, length, and payment-due agreement of a
      recurring pay period for invoicing.
  - name: Contract
    description: >-
      Contracts are used to calculate how we expect to be paid by demand
      partners, and how we pay supply partners.
  - name: Demand Data Import
    description: >-
      Partner provided information that is imported into our systems and
      transformed into external demand events.
  - name: Demand Data Import Configuration
    description: A defined set of standards and processes that can be applied to DDI files
  - name: Demand Sub-Account
    description: >-
      Demand Sub Accounts are child accounts associated with a parent Account
      and represent our demand partners. They can be created per vertical or
      integration type. A demand sub-account represents a single integration
      with a financial institution.
  - name: Demand Sub-Account Deactivation
  - name: Expected Earnings Share
    description: >-
      A representation of the amount of margin we make based off of payout for
      clicks
  - name: External Demand Event
    description: >-
      Events that happen on the demand partner side that contribute to our
      financials and / or modelling.
  - name: Ledger Item
    description: >-
      Ledger items are used to capture and calculate financial informations for
      our partners.
  - name: Ledger Item Reconciliation
    description: >-
      A manual resolving of a Ledger Item -- this is how business will indicate
      that they have either paid, ignored, or otherwise resolved the amount of
      money owed to the Account referenced by the Ledger Item. This, in
      combination with the due date indicated on the invoice will show if we are
      past due on any payable or receivable.
  - name: Ledger Item Settlement
  - name: Sub-Account
    description: A unified view of demand and supply sub-accounts
  - name: Sub-Account External Demand Event
    description: >-
      Events that happen on the demand partner side that contribute to our
      financials and / or modelling and are specifically tied to a sub-account.
  - name: Supply Sub-Account
    description: >-
      Supply Sub Accounts are child accounts associated with a parent Account
      and represent our supply partners. They can be created per vertical or
      integration type A supply sub-account represents a single supply channel
  - name: Supply Sub-Account Deactivation
paths:
  /demandContracts:
    get:
      summary: Get demand contracts
      description: Return demand contracts based on request parameters
      operationId: getDemandContracts
      tags:
        - Contract
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a demand contract
      description: Create a demand contract
      operationId: createDemandContract
      tags:
        - Contract
      security:
        - oauth:
            - 'finance:write'
  '/demandContracts/{id}':
    delete:
      summary: Delete a demand contract
      description: Delete a demand contract
      operationId: deleteDemandContract
      tags:
        - Contract
      security:
        - oauth:
            - 'finance:write'
  /supplyContracts:
    get:
      summary: Get supply contracts
      description: Return supply contracts based on request parameters
      operationId: getSupplyContracts
      tags:
        - Contract
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a supply contract
      description: Create a supply contract based on the request
      operationId: createSupplyContract
      tags:
        - Contract
      security:
        - oauth:
            - 'finance:write'
  '/supplyContracts/{id}':
    delete:
      summary: Delete a supply contract
      description: Delete a supply contract
      operationId: deleteSupplyContract
      tags:
        - Contract
      security:
        - oauth:
            - 'finance:write'
  /demandSubAccounts:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get demand sub-accounts
      description: Get a list of demand sub-accounts filtered by relevant query parameters
      operationId: getDemandSubAccounts
      tags:
        - Demand Sub-Account
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a demand sub-account
      description: Create a demand sub-account based on the request
      operationId: createDemandSubAccount
      tags:
        - Demand Sub-Account
      security:
        - oauth:
            - 'finance:write'
  '/demandSubAccounts/{id}':
    put:
      summary: Update a demand sub-account
      description: >
        Updates the fields of a demand sub-account that corresponds to the ID in
        the URL path, if on exists
      operationId: updateDemandSubAccount
      tags:
        - Demand Sub-Account
      security:
        - oauth:
            - 'finance:write'
    delete:
      summary: Delete a demand sub-account
      description: >
        Soft delete the demand sub-account corresponding to the ID in URL path,
        if one exists
      operationId: deleteDemandSubAccount
      tags:
        - Demand Sub-Account
      security:
        - oauth:
            - 'finance:write'
  /demandSubAccounts/owners:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get a demand sub-account owner
      description: Get a list of Sub Account Owners filtered by relevant query parameters
      operationId: getDemandSubAccountOwners
      tags:
        - Demand Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /demandSubAccounts/searches:
    post:
      summary: Search for demand sub-accounts
      description: >-
        Get a list of Demand sub-accounts based off search parameters sent in
        request body
      operationId: searchDemandSubAccounts
      tags:
        - Demand Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /externalDemandEvents:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get external demand events
      description: Get external demand events
      operationId: getExternalDemandEvents
      tags:
        - External Demand Event
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create external demand event
      description: Create external demand event
      operationId: createExternalDemandEvent
      tags:
        - External Demand Event
      security:
        - oauth:
            - 'finance:write'
  '/externalDemandEvents/{id}':
    delete:
      summary: Delete an external demand event
      description: Delete an external demand event
      operationId: deleteExternalDemandEvent
      tags:
        - External Demand Event
      security:
        - oauth:
            - 'finance:write'
  /subAccounts:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get sub-accounts
      description: Get sub-accounts
      operationId: getSubAccounts
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a sub-account
      description: Create a sub-account based on the request
      operationId: createSubAccount
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:write'
  '/subAccounts/{id}':
    put:
      summary: Update a sub-account
      description: >
        Updates the fields of a sub-account that corresponds to the ID in the
        URL path, if on exists
      operationId: updateSubAccount
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:write'
    delete:
      summary: Delete a sub-account
      description: >
        Soft delete the sub-account corresponding to the ID in URL path, if one
        exists
      operationId: deleteSubAccount
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:write'
  /subAccounts/owners:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get sub-account owners
      description: Get a list of sub-account owners filtered by relevant query parameters
      operationId: getSubAccountOwners
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /subAccounts/search:
    x-lint-skip:
      - path-resource-is-plural
    post:
      summary: Search for sub-accounts
      description: >-
        Get a list of sub-accounts based off search parameters sent in request
        body
      operationId: searchSubAccounts
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /subAccounts/types:
    get:
      summary: Get sub-account types
      operationId: getSubAccountTypes
      tags:
        - Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /supplySubAccounts:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get supply sub-accounts
      description: Get a list of supply sub-accounts filtered by relevant query parameters
      operationId: getSupplySubAccounts
      tags:
        - Supply Sub-Account
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a supply sub-account
      description: Create a supply sub-account
      operationId: createSupplySubAccount
      tags:
        - Supply Sub-Account
      security:
        - oauth:
            - 'finance:write'
  '/supplySubAccounts/{id}':
    put:
      summary: Update a supply sub-account
      description: >
        Updates the fields of a supply sub-account that corresponds to the ID in
        the URL path, if on exists
      operationId: updateSupplySubAccount
      tags:
        - Supply Sub-Account
      security:
        - oauth:
            - 'finance:write'
    delete:
      summary: Delete a supply sub-account
      description: >
        Soft delete the supply sub-account corresponding to the Id in URL path,
        if one exists
      operationId: deleteSupplySubAccount
      tags:
        - Supply Sub-Account
      security:
        - oauth:
            - 'finance:write'
  /supplySubAccounts/owners:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: get a supply sub-account owner
      description: Get a list of Sub Account Owners filtered by relevant query parameters
      operationId: getSupplySubAccountOwners
      tags:
        - Supply Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /supplySubAccounts/searches:
    post:
      summary: Search for supply sub-accounts
      description: >-
        Get a list of supply sub-accounts based off search parameters sent in
        request body
      operationId: searchSupplySubAccounts
      tags:
        - Supply Sub-Account
      security:
        - oauth:
            - 'finance:read'
  /accounts:
    get:
      summary: Get accounts
      description: Return accounts based upon request parameters
      operationId: getAccounts
      tags:
        - Account
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a account
      description: Create a account
      operationId: createAccount
      tags:
        - Account
      security:
        - oauth:
            - 'finance:write'
  '/accounts/{id}':
    delete:
      summary: Delete an account
      description: Delete an account
      operationId: deleteAccount
      tags:
        - Account
      security:
        - oauth:
            - 'finance:write'
    put:
      summary: Update an account
      description: >
        Updates the fields of an Account that corresponds to the id in the URL
        path, if on exists
      operationId: updateAccount
      tags:
        - Account
      security:
        - oauth:
            - 'finance:write'
  /accounts/owners:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get account owners
      description: |
        Return a list of account owners based on request parameters
      operationId: getAccountOwners
      tags:
        - Account
      security:
        - oauth:
            - 'finance:read'
  '/accounts/owners/{id}':
    delete:
      summary: Delete an account owner
      description: Delete an account owner
      operationId: deleteAccountOwner
      tags:
        - Account
      security:
        - oauth:
            - 'finance:write'
  /accountAdjustments:
    get:
      summary: Get account adjustments
      description: |
        Returns a list of account adjustments that match the specified criteria
      operationId: getAccountAdjustments
      tags:
        - Account Adjustment
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create an account adjustment
      operationId: createAccountAdjustment
      tags:
        - Account Adjustment
      security:
        - oauth:
            - 'finance:write'
  '/accountAdjustments/{id}':
    delete:
      summary: Delete an account adjustment
      description: >
        Soft delete the account adjustment corresponding to the specified ID in
        URL path, if one exists
      operationId: deleteAccountAdjustment
      tags:
        - Account Adjustment
      security:
        - oauth:
            - 'finance:write'
  /adjustmentsReasons:
    get:
      summary: Get valid account adjustment reasons
      operationId: getAdjustmentReasons
      tags:
        - Account Adjustment
      security:
        - oauth:
            - 'finance:read'
  /billingCycles:
    get:
      summary: Get billing cycles
      description: |
        Return a list of billing cycles that match the specified criteria
      operationId: getBillingCycles
      tags:
        - Billing Cycle
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Record a billing cycle
      operationId: createBillingCycle
      tags:
        - Billing Cycle
      security:
        - oauth:
            - 'finance:write'
  '/billingCycles/{id}':
    put:
      summary: Update a billing cycle
      description: >
        Updates the memo field of the ledger item corresponding to the specified
        ID in URL path, if one exists
      operationId: updateBillingCycle
      tags:
        - Billing Cycle
      security:
        - oauth:
            - 'finance:write'
    delete:
      summary: Delete a billing cycle
      description: >
        Soft delete the billing cycle corresponding to the specified ID in URL
        path, if one exists
      operationId: deleteBillingCycle
      tags:
        - Billing Cycle
      security:
        - oauth:
            - 'finance:write'
  /billingCycles/generateLedgerItems:
    post:
      summary: Generate ledger items
      description: |
        Generate a list of ledger items based on a specifed date
      operationId: generateLedgerItemsForDate
      tags:
        - Billing Cycle
      security:
        - oauth:
            - 'finance:write'
  /ledgerItems:
    get:
      summary: Get ledger items
      description: |
        Returns a list of ledger items that match the specified criteria.
      operationId: getLedgerItems
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create ledger item
      operationId: createLedgerItem
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:write'
  '/ledgerItems/{id}':
    get:
      summary: Get a ledger item
      description: >
        Returns the ledger item corresponding to the specified ID in the URL
        path, if one exists.
      operationId: getLedgerItem
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:read'
    put:
      summary: Update a ledger item
      description: >
        Updates the memo field of the ledger item corresponding to the specified
        ID in URL path, if one exists
      operationId: updateLedgerItem
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:write'
    delete:
      summary: Delete a ledger item
      description: >
        Soft delete the ledger item corresponding to the specified ID in URL
        path, if one exists
      operationId: deleteLedgerItem
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:write'
  '/ledgerItems/{id}/recreate':
    x-lint-skip:
      - path-resource-is-plural
    post:
      summary: Recreate a ledger item
      operationId: recreateLedgerItem
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:write'
  /ledgerItems/oneOffs:
    post:
      x-implementation-state: none
      summary: Create a one off ledger item
      operationId: createOneOffLedgerItem
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:write'
  /ledgerItemRegenerationBatches:
    post:
      summary: Regenerate multiple ledger items
      operationId: createLedgerItemRegenerationBatch
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:write'
  /payableSummaries:
    get:
      summary: Get payable summaries
      description: |
        Returns a list of payable summaries that match the specified criteria.
      operationId: getPayableSummaries
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:read'
  /receivableSummaries:
    get:
      summary: Get receivable summaries
      description: >
        Returns a list of receivable summaries that match the specified
        criteria.
      operationId: getReceivableSummaries
      tags:
        - Ledger Item
      security:
        - oauth:
            - 'finance:read'
  /ledgerItemReconciliations:
    get:
      summary: Get ledger item reconiliations
      description: >
        Returns a list of ledger item reconciliations that match the specified
        criteria.
      operationId: getLedgerItemReconciliations
      tags:
        - Ledger Item Reconciliation
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a ledger item reconciliation
      operationId: createLedgerItemReconciliation
      tags:
        - Ledger Item Reconciliation
      security:
        - oauth:
            - 'finance:write'
    delete:
      summary: Delete multiple ledger item reconciliations
      description: >
        Soft delete multiple ledger item reconciliations that match the ids
        provided in the URL path
      operationId: deleteLedgerItemReconciliations
      tags:
        - Ledger Item Reconciliation
      security:
        - oauth:
            - 'finance:write'
  '/ledgerItemReconciliations/{id}':
    get:
      summary: Get a ledger item reconciliation
      description: >
        Returns the ledger item reconciliation corresponding to the specified ID
        in the URL path, if one exists.
      operationId: getLedgerItemReconciliation
      tags:
        - Ledger Item Reconciliation
      security:
        - oauth:
            - 'finance:read'
  /demandDataImports:
    get:
      summary: Get demand data imports
      description: Return demand data imports based upon request parameters
      operationId: getDemandDataImports
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Demand Data Import
    post:
      summary: Create a demand data import
      description: Create a demand data import
      operationId: createDemandDataImport
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Demand Data Import
  '/demandDataImports/{id}':
    delete:
      summary: Delete a demand data import
      description: Delete a demand data import
      operationId: deleteDemandDataImport
      tags:
        - Demand Data Import
      security:
        - oauth:
            - 'finance:write'
  /demandDataImportSummaries:
    get:
      summary: Get demand data import summaries
      description: Return demand data import summaries based upon request parameters
      operationId: getDemandDataImportSummaries
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Demand Data Import
  /demandDataImportConfigurations:
    get:
      summary: Get demand data import configurations
      description: Return demand data import configurations based upon request parameters
      operationId: getDemandDataImportConfigurations
      tags:
        - Demand Data Import Configuration
      security:
        - oauth:
            - 'finance:read'
    post:
      summary: Create a demand data import configuration
      description: Create a demand data import configuration
      operationId: createDemandDataImportConfiguration
      tags:
        - Demand Data Import Configuration
      security:
        - oauth:
            - 'finance:write'
  '/demandDataImportConfigurations/{id}':
    delete:
      summary: Delete a demand data import configuration
      description: Delete a demand data import configuration
      operationId: deleteDemandDataImportConfiguration
      tags:
        - Demand Data Import Configuration
      security:
        - oauth:
            - 'finance:write'
  /subAccountExternalDemandEvents:
    get:
      summary: Get sub-account external demand events
      description: Get sub-account external demand events.
      operationId: getSubAccountExternalDemandEvents
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Sub-Account External Demand Event
    post:
      summary: Create a sub-account external demand event
      description: Create a sub account external demand event
      operationId: createSubAccountExternalDemandEvent
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Sub-Account External Demand Event
  '/subAccountExternalDemandEvents/{id}':
    delete:
      summary: Delete a sub-account external demand event
      description: Delete a sub-account external demand event
      operationId: deleteSubAccountExternalDemandEvent
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Sub-Account External Demand Event
  /expectedEarningsShare:
    x-lint-skip:
      - path-resource-is-plural
    get:
      summary: Get expected earnings shares
      description: Get expected earnings shares
      operationId: getExpectedEarningsShares
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Expected Earnings Share
    post:
      summary: Create an expected earnings share
      description: Create an expected earnings share
      operationId: createExpectedEarningsShare
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Expected Earnings Share
  /expectedEarningsShare/active:
    x-lint-skip:
      - path-resource-is-plural
    get:
      summary: Return the a list of active expected earnings shares
      operationId: getActiveExpectedEarningsShares
      tags:
        - Expected Earnings Share
      security:
        - oauth:
            - 'finance:read'
  /expectedEarningsShare/default:
    x-lint-skip:
      - path-resource-is-plural
    get:
      summary: Return default expected earnings shares
      operationId: getDefaultExpectedEarningsShares
      tags:
        - Expected Earnings Share
      security:
        - oauth:
            - 'finance:read'
  /expectedEarningsShare/history:
    x-lint-skip:
      - path-resource-is-plural
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Return historical of expected earnings shares
      operationId: getExpectedEarningsSharesHistory
      tags:
        - Expected Earnings Share
      security:
        - oauth:
            - 'finance:read'
  /accountDeactivations:
    get:
      summary: Get account deactivations
      description: Return account deactivations based upon request parameters
      operationId: getAccountDeactivations
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Account Deactivation
    post:
      summary: Create account deactivations
      description: Create account deactivations
      operationId: createAccountDeactivation
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Account Deactivation
  '/accountDeactivations/{id}':
    delete:
      summary: Delete a account deactivation
      description: Delete a account deactivation
      operationId: deleteAccountDeactivation
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Account Deactivation
  /demandSubAccountDeactivations:
    get:
      summary: Get demand sub-account deactivations
      description: Return demand sub-account deactivations based upon request parameters
      operationId: getDemandSubAccountDeactivations
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Demand Sub-Account Deactivation
    post:
      summary: Create demand sub-account deactivations
      description: Create demand sub-account deactivations
      operationId: createDemandSubAccountDeactivation
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Demand Sub-Account Deactivation
  '/demandSubAccountDeactivations/{id}':
    delete:
      summary: Delete a demand sub-account deactivation
      description: Delete a demand sub-account deactivation
      operationId: deleteDemandSubAccountDeactivation
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Demand Sub-Account Deactivation
  /supplySubAccountDeactivations:
    get:
      summary: Get supply sub-account deactivations
      description: Return supply sub-account deactivations based upon request parameters
      operationId: getSupplySubAccountDeactivations
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Supply Sub-Account Deactivation
    post:
      summary: Create supply sub-account deactivations
      description: Create supply sub-account deactivations
      operationId: createSupplySubAccountDeactivation
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Supply Sub-Account Deactivation
  '/supplySubAccountDeactivations/{id}':
    delete:
      summary: Delete a supply sub-account deactivation
      description: Delete a supply sub-account deactivation
      operationId: deleteSupplySubAccountDeactivation
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Supply Sub-Account Deactivation
  /ledgerItemSettlements:
    get:
      x-implementation-state: none
      summary: Get ledger item settlements
      description: Return ledger item settlements based upon request parameters
      operationId: getLedgerItemSettlements
      security:
        - oauth:
            - 'finance:read'
      tags:
        - Ledger Item Settlement
    post:
      x-implementation-state: none
      summary: Create ledger item settlements
      description: Create ledger item settlements
      operationId: createLedgerItemSettlements
      security:
        - oauth:
            - 'finance:write'
      tags:
        - Ledger Item Settlement