openapi: 3.0.3
info:
  title: originator
  description: description
  version: 1.9.0
  contact:
    name: Offers Team
    url: >-
      https://evenfinancial.atlassian.net/wiki/spaces/ENG/pages/12124290/Offers+Team
servers:
  - url: 'https://api.evenfinancial.com/originator'
    description: Prod
  - url: 'https://dev-api.evenfinancial.com/originator'
    description: Dev
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /auth/accessTokens
          scopes:
            'originator:rateTables:read': Allows read access to `RateTables`
            'originator:rate_table:read': 'Deprecated alias of `originator:rateTables:read`'
            'originator:rateTables:create': Allows create access to `RateTables`
            'originator:admin:read': Allows read access to all admin endpoints in originator
            'originator:admin:write': Allows write access to all admin endpoints in originator
tags:
  - name: Demand API Filter
  - name: Life Insurance
  - name: Mock Rate Table
  - name: Offer
  - name: Offer Deactivation
  - name: Offer Rule
  - name: Payout Ceiling
  - name: Pre-Select Rule
  - name: Preview Offer
  - name: Pricing Control
  - name: Rate Table
    description: >-
      The `RateTable` object contains offers relating to one or more product
      types customized for a specific `Lead`. It only contains offers for
      product types set on the `Lead`.
  - name: Rule Demand API Filter
  - name: Static Offer
  - name: Supply Demand Inclusion
paths:
  '/rateTables/{uuid}':
    get:
      summary: Get a rate table
      description: Return a rate table for a UUID
      operationId: getRateTable
      tags:
        - Rate Table
      security:
        - oauth:
            - 'originator:rateTables:read'
            - 'originator:rate_table:read'
  /preview/creditCardOffers:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get credit card preview offers
      description: Get credit card preview offers
      operationId: getPreviewCreditCardOffers
      tags:
        - Preview Offer
      security:
        - oauth:
            - 'originator:rateTables:read'
  /preview/loanOffers:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get loan preview offers
      description: Get loan preview offers
      operationId: getPreviewLoanOffers
      tags:
        - Preview Offer
      security:
        - oauth:
            - 'originator:rateTables:read'
  /preview/savingsOffers:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get savings preview offers
      description: Get savings preview offers
      operationId: getPreviewSavingsOffers
      tags:
        - Preview Offer
      security:
        - oauth:
            - 'originator:rateTables:read'
  /admin/rateTables:
    get:
      summary: Get a rate table
      description: get rate table
      operationId: getAdminRateTable
      tags:
        - Rate Table
      security:
        - oauth:
            - 'originator:admin:read'
    post:
      summary: Create a rate table
      description: Create a rate table
      operationId: createRateTable
      tags:
        - Rate Table
      security:
        - oauth:
            - 'originator:admin:write'
  /admin/demandApiFilters:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get demand API filters
      description: Get demand API filters
      operationId: getDemandApiFilters
      tags:
        - Demand API Filter
      security:
        - oauth:
            - 'originator:admin:read'
  /admin/ruleDemandApiFilters:
    get:
      summary: Get Rule Demand API Filters
      description: Get Rule Demand API Filters based on request parameters
      operationId: getRuleDemandApiFilters
      tags:
        - Rule Demand API Filter
      security:
        - oauth:
            - 'originator:admin:read'
  /admin/supplyDemandInclusions:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get supply / demand inclusions
      description: Return supply / demand inclusions based on request parameters
      operationId: getSupplyDemandInclusions
      tags:
        - Supply Demand Inclusion
      security:
        - oauth:
            - 'originator:admin:read'
    post:
      summary: Create a supply / demand inclusion
      description: Create a supply / demand inclusion
      operationId: createSupplyDemandInclusion
      tags:
        - Supply Demand Inclusion
      security:
        - oauth:
            - 'originator:admin:write'
  '/admin/supplyDemandInclusions/{id}':
    delete:
      summary: Delete a supply / demand inclusion
      description: Delete a supply / demand inclusion
      operationId: deleteSupplyDemandInclusion
      tags:
        - Supply Demand Inclusion
      security:
        - oauth:
            - 'originator:admin:write'
  /admin/offerRules:
    post:
      summary: Create an offer rule
      description: Create an offer rule
      operationId: createOfferRule
      tags:
        - Offer Rule
      security:
        - oauth:
            - 'originator:admin:write'
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get offer rules
      description: Get offer rules
      operationId: getOfferRules
      tags:
        - Offer Rule
      security:
        - oauth:
            - 'originator:admin:read'
  '/admin/offerRules/root/{rootId}':
    x-lint-skip:
      - path-resource-is-plural
    patch:
      summary: Update an offer rule
      description: Update an offer rule
      operationId: updateOfferRule
      security:
        - oauth:
            - 'originator:admin:write'
      tags:
        - Offer Rule
    delete:
      summary: Delete an offer rule
      description: Delete an offer rule
      operationId: deleteOfferRule
      security:
        - oauth:
            - 'originator:admin:write'
      tags:
        - Offer Rule
  /admin/offers:
    get:
      summary: Get offers
      description: Get offers
      operationId: getOffers
      tags:
        - Offer
      security:
        - oauth:
            - 'originator:admin:read'
  /admin/staticOffers:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get static offers
      description: Get static offers
      operationId: getStaticOffers
      tags:
        - Static Offer
      security:
        - oauth:
            - 'originator:admin:read'
  /admin/mockRateTables:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get mock rate tables
      description: Get mock rate tables
      operationId: getMockRateTables
      tags:
        - Mock Rate Table
    post:
      summary: Create a mock rate table
      description: Create a mock rate table
      operationId: createMockRateTable
      tags:
        - Mock Rate Table
      security:
        - oauth:
            - 'originator:admin:write'
  '/admin/mockRateTables/{id}':
    delete:
      summary: Delete a mock rate table
      description: Delete a mock rate table
      operationId: deleteMockRateTable
      tags:
        - Mock Rate Table
      security:
        - oauth:
            - 'originator:admin:write'
  /admin/mockRateTableStaticOffers:
    get:
      x-lint-skip:
        - index-endpoint-has-limit
      summary: Get mock rate table static offers
      description: Get mock rate table static offers
      operationId: getMockRateTableStaticOffers
      tags:
        - Mock Rate Table
      security:
        - oauth:
            - 'originator:admin:read'
    post:
      summary: Create a mock rate table static offer
      description: Create a mock rate table static offer
      operationId: createMockRateTableStaticOffer
      tags:
        - Mock Rate Table
      security:
        - oauth:
            - 'originator:admin:write'
  '/admin/mockRateTableStaticOffers/{id}':
    delete:
      summary: Delete a mock rate table static offer
      description: Delete a mock rate table static offer
      operationId: deleteMockRateTableStaticOffer
      tags:
        - Mock Rate Table
      security:
        - oauth:
            - 'originator:admin:write'
  /admin/preSelectRules:
    get:
      summary: Get pre-select rules
      description: Get pre-select rules
      operationId: getPreSelectRules
      tags:
        - Pre-Select Rule
      security:
        - oauth:
            - 'originator:admin:read'
    post:
      summary: Create a pre-select rule
      description: Create a pre-select rule
      operationId: createPreSelectRule
      tags:
        - Pre-Select Rule
      security:
        - oauth:
            - 'originator:admin:write'
  '/admin/preSelectRules/{id}':
    delete:
      summary: Delete a pre-select rule
      description: Delete a pre-select rule
      operationId: deletePreSelectRule
      tags:
        - Pre-Select Rule
      security:
        - oauth:
            - 'originator:admin:write'
    put:
      summary: Update a pre-select rule
      description: Update a pre-select rule
      operationId: updatePreSelectRule
      tags:
        - Pre-Select Rule
      security:
        - oauth:
            - 'originator:admin:write'
  /admin/preSelectRuleSummaries:
    get:
      summary: Get pre-select rule summaries
      description: >
        Returns a list of pre-select rule summaries that match the specified
        criteria.
      operationId: getPreselectRuleSummaries
      tags:
        - Pre-Select Rule
      security:
        - oauth:
            - 'originator:admin:read'
  /lifeInsurance/searches:
    post:
      summary: Creates rate table with single life insurance offer
      description: |-
        - Call leap life API proxy
        - Create rate table with single life insurance offer
      operationId: createLifeInsuranceSearch
      tags:
        - Life Insurance
      security:
        - oauth:
            - 'originator:rateTables:create'
  /admin/payoutCeilings:
    get:
      summary: Get payout ceilings
      description: Get payout ceilings
      operationId: getPayoutCeilings
      tags:
        - Payout Ceiling
      security:
        - oauth:
            - 'originator:admin:read'
    post:
      summary: Create a payout ceiling
      description: Create a payout ceiling
      operationId: createPayoutCeiling
      tags:
        - Payout Ceiling
      security:
        - oauth:
            - 'originator:admin:write'
  '/admin/payoutCeilings/{id}':
    put:
      summary: Update a payout ceiling
      description: Update a payout ceiling
      operationId: updatePayoutCeiling
      tags:
        - Payout Ceiling
      security:
        - oauth:
            - 'originator:admin:write'
    delete:
      summary: Delete a payout ceiling
      description: Delete a payout ceiling
      operationId: deletePayoutCeiling
      tags:
        - Payout Ceiling
      security:
        - oauth:
            - 'originator:admin:write'
  /offerDeactivations:
    get:
      summary: Get offer deactivations
      description: Return offer deactivations based upon request parameters
      operationId: getOfferDeactivations
      security:
        - oauth:
            - 'originator:admin:read'
      tags:
        - Offer Deactivation
    post:
      summary: Create offer deactivations
      description: Create offer deactivations
      operationId: createOfferDeactivation
      security:
        - oauth:
            - 'originator:admin:write'
      tags:
        - Offer Deactivation
  '/offerDeactivations/{id}':
    delete:
      summary: Delete a offer deactivation
      description: Delete a offer deactivation
      operationId: deleteOfferDeactivation
      security:
        - oauth:
            - 'originator:admin:write'
      tags:
        - Offer Deactivation
  /admin/pricingControlSummaries:
    get:
      summary: Get pricing control summaries
      description: >
        Returns a list of pricing control summaries summaries that match the
        specified criteria.
      operationId: getPricingControlSummaries
      tags:
        - Pricing Control
      security:
        - oauth:
            - 'originator:admin:read'