//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenSubAccountOwner: BirchModel, Decodable, AutoEquatable {

    public var id: Int

    public var subAccountId: Int

    public var createdAt: DateTime

    public var createdBy: ID

    public var deletedAt: DateTime?

    public var deletedBy: ID?

    public var partnerManager: ID?

    public var yieldManager: ID?

    public init(id: Int, subAccountId: Int, createdAt: DateTime, createdBy: ID, deletedAt: DateTime? = nil, deletedBy: ID? = nil, partnerManager: ID? = nil, yieldManager: ID? = nil) {
        self.id = id
        self.subAccountId = subAccountId
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.deletedAt = deletedAt
        self.deletedBy = deletedBy
        self.partnerManager = partnerManager
        self.yieldManager = yieldManager
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decode("id")
        subAccountId = try container.decode("subAccountId")
        createdAt = try container.decode("createdAt")
        createdBy = try container.decode("createdBy")
        deletedAt = try container.decodeIfPresent("deletedAt")
        deletedBy = try container.decodeIfPresent("deletedBy")
        partnerManager = try container.decodeIfPresent("partnerManager")
        yieldManager = try container.decodeIfPresent("yieldManager")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(id, forKey: "id")
        try container.encode(subAccountId, forKey: "subAccountId")
        try container.encode(createdAt, forKey: "createdAt")
        try container.encode(createdBy, forKey: "createdBy")
        try container.encodeIfPresent(deletedAt, forKey: "deletedAt")
        try container.encodeIfPresent(deletedBy, forKey: "deletedBy")
        try container.encodeIfPresent(partnerManager, forKey: "partnerManager")
        try container.encodeIfPresent(yieldManager, forKey: "yieldManager")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenSubAccountOwner else { return false }
      guard self.id == object.id else { return false }
      guard self.subAccountId == object.subAccountId else { return false }
      guard self.createdAt == object.createdAt else { return false }
      guard self.createdBy == object.createdBy else { return false }
      guard self.deletedAt == object.deletedAt else { return false }
      guard self.deletedBy == object.deletedBy else { return false }
      guard self.partnerManager == object.partnerManager else { return false }
      guard self.yieldManager == object.yieldManager else { return false }
      return true
    }

    public static func == (lhs: EvenSubAccountOwner, rhs: EvenSubAccountOwner) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
