//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenSupplyFeatureFlag: BirchModel, Decodable, AutoEquatable {

    public var supplySubAccountId: Int

    public init(supplySubAccountId: Int) {
        self.supplySubAccountId = supplySubAccountId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        supplySubAccountId = try container.decode("supplySubAccountId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(supplySubAccountId, forKey: "supplySubAccountId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenSupplyFeatureFlag else { return false }
      guard self.supplySubAccountId == object.supplySubAccountId else { return false }
      return true
    }

    public static func == (lhs: EvenSupplyFeatureFlag, rhs: EvenSupplyFeatureFlag) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
