//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenOtherRevenueRevenueClause: BirchModel, Decodable, AutoEquatable {

    public init() {
    }

    public required init(from decoder: Decoder) throws {
    }

    public func encode(to encoder: Encoder) throws {
    }

    public func isEqual(to object: Any?) -> Bool {
      guard object is EvenOtherRevenueRevenueClause else { return false }
      return true
    }

    public static func == (lhs: EvenOtherRevenueRevenueClause, rhs: EvenOtherRevenueRevenueClause) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
