//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenSupplySubAccountUpdateData: BirchModel, Decodable, AutoEquatable {

    public init() {
    }

    public required init(from decoder: Decoder) throws {
    }

    public func encode(to encoder: Encoder) throws {
    }

    public func isEqual(to object: Any?) -> Bool {
      guard object is EvenSupplySubAccountUpdateData else { return false }
      return true
    }

    public static func == (lhs: EvenSupplySubAccountUpdateData, rhs: EvenSupplySubAccountUpdateData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
