//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenAccountOwnersWriteData: BirchModel, Decodable, AutoEquatable {

    public var supplyManager: String

    public var demandManager: String

    public var supplyYieldManager: String

    public var demandYieldManager: String

    public init(supplyManager: String, demandManager: String, supplyYieldManager: String, demandYieldManager: String) {
        self.supplyManager = supplyManager
        self.demandManager = demandManager
        self.supplyYieldManager = supplyYieldManager
        self.demandYieldManager = demandYieldManager
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        supplyManager = try container.decode("supplyManager")
        demandManager = try container.decode("demandManager")
        supplyYieldManager = try container.decode("supplyYieldManager")
        demandYieldManager = try container.decode("demandYieldManager")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(supplyManager, forKey: "supplyManager")
        try container.encode(demandManager, forKey: "demandManager")
        try container.encode(supplyYieldManager, forKey: "supplyYieldManager")
        try container.encode(demandYieldManager, forKey: "demandYieldManager")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenAccountOwnersWriteData else { return false }
      guard self.supplyManager == object.supplyManager else { return false }
      guard self.demandManager == object.demandManager else { return false }
      guard self.supplyYieldManager == object.supplyYieldManager else { return false }
      guard self.demandYieldManager == object.demandYieldManager else { return false }
      return true
    }

    public static func == (lhs: EvenAccountOwnersWriteData, rhs: EvenAccountOwnersWriteData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
