//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenSubAccountFeatureFlag: BirchModel, Decodable, AutoEquatable {

    public var id: Int

    public var featureId: String

    public init(id: Int, featureId: String) {
        self.id = id
        self.featureId = featureId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decode("id")
        featureId = try container.decode("featureId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(id, forKey: "id")
        try container.encode(featureId, forKey: "featureId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenSubAccountFeatureFlag else { return false }
      guard self.id == object.id else { return false }
      guard self.featureId == object.featureId else { return false }
      return true
    }

    public static func == (lhs: EvenSubAccountFeatureFlag, rhs: EvenSubAccountFeatureFlag) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
