//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum EvenTransformerType: String, Codable, Equatable, CaseIterable {
    case addIntToValue = "add_int_to_value"
    case excelTimestamp = "excel_timestamp"
    case noOp = "no_op"
    case stripPrefix = "strip_prefix"
    case stripSuffix = "strip_suffix"
    case timestamp = "timestamp"
    case uuid = "uuid"
    case isNotNull = "is_not_null"
    case undecodable

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(String.self)
        self = EvenTransformerType(rawValue: rawValue) ?? .undecodable
    }
}
