//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenGenericImportConfigurationDetails: BirchModel, Decodable, AutoEquatable {

    public var revenueAmountProcessor: EvenAppliedTimestampProcessor

    public var revenueTimestampProcessor: EvenAppliedTimestampProcessor

    public init(revenueAmountProcessor: EvenAppliedTimestampProcessor, revenueTimestampProcessor: EvenAppliedTimestampProcessor) {
        self.revenueAmountProcessor = revenueAmountProcessor
        self.revenueTimestampProcessor = revenueTimestampProcessor
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        revenueAmountProcessor = try container.decode("revenueAmountProcessor")
        revenueTimestampProcessor = try container.decode("revenueTimestampProcessor")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(revenueAmountProcessor, forKey: "revenueAmountProcessor")
        try container.encode(revenueTimestampProcessor, forKey: "revenueTimestampProcessor")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenGenericImportConfigurationDetails else { return false }
      guard self.revenueAmountProcessor == object.revenueAmountProcessor else { return false }
      guard self.revenueTimestampProcessor == object.revenueTimestampProcessor else { return false }
      return true
    }

    public static func == (lhs: EvenGenericImportConfigurationDetails, rhs: EvenGenericImportConfigurationDetails) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
