//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenLedgerItemRecreateData: BirchModel, Decodable, AutoEquatable {

    public var copyAdjustments: Bool

    public init(copyAdjustments: Bool) {
        self.copyAdjustments = copyAdjustments
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        copyAdjustments = try container.decode("copyAdjustments")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(copyAdjustments, forKey: "copyAdjustments")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenLedgerItemRecreateData else { return false }
      guard self.copyAdjustments == object.copyAdjustments else { return false }
      return true
    }

    public static func == (lhs: EvenLedgerItemRecreateData, rhs: EvenLedgerItemRecreateData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
