//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenBillingCycleUpdateData: BirchModel, Decodable, AutoEquatable {

    public var endDate: DateDay

    public init(endDate: DateDay) {
        self.endDate = endDate
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        endDate = try container.decode("endDate")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(endDate, forKey: "endDate")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenBillingCycleUpdateData else { return false }
      guard self.endDate == object.endDate else { return false }
      return true
    }

    public static func == (lhs: EvenBillingCycleUpdateData, rhs: EvenBillingCycleUpdateData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
