//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum EvenLedgerItemSettlementStatus: String, Codable, Equatable, CaseIterable {
    case pending = "pending"
    case started = "started"
    case success = "success"
    case skipped = "skipped"
    case error = "error"
    case undecodable

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(String.self)
        self = EvenLedgerItemSettlementStatus(rawValue: rawValue) ?? .undecodable
    }
}
