//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum EvenLedgerItemType: String, Codable, Equatable, CaseIterable {
    case payable = "payable"
    case receivable = "receivable"
    case unknown = "unknown"
    case undecodable

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(String.self)
        self = EvenLedgerItemType(rawValue: rawValue) ?? .undecodable
    }
}
