//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenLegacySubAccountCreateData: BirchModel, Decodable, AutoEquatable {

    public var accountId: Int

    public var subAccountType: EvenSubAccountTypeKey

    public var name: String

    public var displayName: String

    public var roles: [String]

    /** A.M. Best's rating */
    public var amBestRating: String?

    public var foundedYear: Int?

    public var imageUrl: String?

    public var notes: String?

    /** Override the default display text for indicating a pre-selected offer if shouldDisplayPreSelect is true. */
    public var preSelectTextOverride: String?

    /** Override the default auto-generated call to action subtext for issuers */
    public var subtextOverride: String?

    /** Product type exclusive to supply sub accounts */
    public var supplyProductType: [String]?

    public init(accountId: Int, subAccountType: EvenSubAccountTypeKey, name: String, displayName: String, roles: [String], amBestRating: String? = nil, foundedYear: Int? = nil, imageUrl: String? = nil, notes: String? = nil, preSelectTextOverride: String? = nil, subtextOverride: String? = nil, supplyProductType: [String]? = nil) {
        self.accountId = accountId
        self.subAccountType = subAccountType
        self.name = name
        self.displayName = displayName
        self.roles = roles
        self.amBestRating = amBestRating
        self.foundedYear = foundedYear
        self.imageUrl = imageUrl
        self.notes = notes
        self.preSelectTextOverride = preSelectTextOverride
        self.subtextOverride = subtextOverride
        self.supplyProductType = supplyProductType
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        accountId = try container.decode("accountId")
        subAccountType = try container.decode("subAccountType")
        name = try container.decode("name")
        displayName = try container.decode("displayName")
        roles = try container.decodeArray("roles")
        amBestRating = try container.decodeIfPresent("amBestRating")
        foundedYear = try container.decodeIfPresent("foundedYear")
        imageUrl = try container.decodeIfPresent("imageUrl")
        notes = try container.decodeIfPresent("notes")
        preSelectTextOverride = try container.decodeIfPresent("preSelectTextOverride")
        subtextOverride = try container.decodeIfPresent("subtextOverride")
        supplyProductType = try container.decodeArrayIfPresent("supplyProductType")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(accountId, forKey: "accountId")
        try container.encode(subAccountType, forKey: "subAccountType")
        try container.encode(name, forKey: "name")
        try container.encode(displayName, forKey: "displayName")
        try container.encode(roles, forKey: "roles")
        try container.encodeIfPresent(amBestRating, forKey: "amBestRating")
        try container.encodeIfPresent(foundedYear, forKey: "foundedYear")
        try container.encodeIfPresent(imageUrl, forKey: "imageUrl")
        try container.encodeIfPresent(notes, forKey: "notes")
        try container.encodeIfPresent(preSelectTextOverride, forKey: "preSelectTextOverride")
        try container.encodeIfPresent(subtextOverride, forKey: "subtextOverride")
        try container.encodeIfPresent(supplyProductType, forKey: "supplyProductType")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenLegacySubAccountCreateData else { return false }
      guard self.accountId == object.accountId else { return false }
      guard self.subAccountType == object.subAccountType else { return false }
      guard self.name == object.name else { return false }
      guard self.displayName == object.displayName else { return false }
      guard self.roles == object.roles else { return false }
      guard self.amBestRating == object.amBestRating else { return false }
      guard self.foundedYear == object.foundedYear else { return false }
      guard self.imageUrl == object.imageUrl else { return false }
      guard self.notes == object.notes else { return false }
      guard self.preSelectTextOverride == object.preSelectTextOverride else { return false }
      guard self.subtextOverride == object.subtextOverride else { return false }
      guard self.supplyProductType == object.supplyProductType else { return false }
      return true
    }

    public static func == (lhs: EvenLegacySubAccountCreateData, rhs: EvenLegacySubAccountCreateData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
