//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenCostPerSubIdValue: BirchModel, Decodable, AutoEquatable {

    public var key: String

    public var value: Double

    public init(key: String, value: Double) {
        self.key = key
        self.value = value
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        key = try container.decode("key")
        value = try container.decode("value")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(key, forKey: "key")
        try container.encode(value, forKey: "value")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenCostPerSubIdValue else { return false }
      guard self.key == object.key else { return false }
      guard self.value == object.value else { return false }
      return true
    }

    public static func == (lhs: EvenCostPerSubIdValue, rhs: EvenCostPerSubIdValue) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
