//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenCostPerCreditCardApprovedRevenueClause: BirchModel, Decodable, AutoEquatable {

    public var cost: Double

    public init(cost: Double) {
        self.cost = cost
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        cost = try container.decode("cost")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(cost, forKey: "cost")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenCostPerCreditCardApprovedRevenueClause else { return false }
      guard self.cost == object.cost else { return false }
      return true
    }

    public static func == (lhs: EvenCostPerCreditCardApprovedRevenueClause, rhs: EvenCostPerCreditCardApprovedRevenueClause) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
