//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenImportConfigurationDetails: BirchModel, Decodable, AutoEquatable {

    public var key: String

    public init(key: String) {
        self.key = key
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        key = try container.decode("key")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(key, forKey: "key")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenImportConfigurationDetails else { return false }
      guard self.key == object.key else { return false }
      return true
    }

    public static func == (lhs: EvenImportConfigurationDetails, rhs: EvenImportConfigurationDetails) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
