//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EvenDemandSubAccountDeactivationCreateData: BirchModel, Decodable, AutoEquatable {

    /** Identifiers for the demand sub accounts that are deactivated.
 */
    public var demandSubAccountIds: [Int]

    /** Reason why the demand sub accounts were deactivated.
 */
    public var deactivationReason: String?

    public init(demandSubAccountIds: [Int], deactivationReason: String? = nil) {
        self.demandSubAccountIds = demandSubAccountIds
        self.deactivationReason = deactivationReason
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        demandSubAccountIds = try container.decodeArray("demandSubAccountIds")
        deactivationReason = try container.decodeIfPresent("deactivationReason")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(demandSubAccountIds, forKey: "demandSubAccountIds")
        try container.encodeIfPresent(deactivationReason, forKey: "deactivationReason")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EvenDemandSubAccountDeactivationCreateData else { return false }
      guard self.demandSubAccountIds == object.demandSubAccountIds else { return false }
      guard self.deactivationReason == object.deactivationReason else { return false }
      return true
    }

    public static func == (lhs: EvenDemandSubAccountDeactivationCreateData, rhs: EvenDemandSubAccountDeactivationCreateData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
