//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

public enum EvenOrder: String, Codable, Equatable, CaseIterable {
    case asc = "asc"
    case desc = "desc"
    case undecodable

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(String.self)
        self = EvenOrder(rawValue: rawValue) ?? .undecodable
    }
}
