type: object
title: Cost Per Completed Application
required:
  - cost
properties:
  cost:
    type: number
    multipleOf: 0.01
    title: Amount (in $ USD)
    minimum: 0.01
allOf:
  - $ref: ../abstractPayoutClause.yml
